# Generated by Django 5.0.8 on 2024-08-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0005_alter_equipmentrating_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="condition",
            field=models.CharField(max_length=200),
        ),
    ]
