# Generated by Django 5.0.8 on 2024-08-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0006_alter_equipment_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="condition",
            field=models.CharField(
                choices=[("New", "New"), ("Used", "Used")],
                default="New",
                max_length=200,
            ),
        ),
    ]
