# Generated by Django 5.0.8 on 2024-08-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20220227_0753"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="twilio_user_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
