# Generated by Django 5.0.8 on 2024-08-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_twilio_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="secondary_phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="state",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=10, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
