# Generated by Django 5.0.8 on 2024-08-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_address_remove_user_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Address of User"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="City of User"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="secondary_phone_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Secondary Phone Number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="State of User"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=10, null=True, unique=True, verbose_name="Phone Number"
            ),
        ),
    ]
